# Generated by Django 6.0.1 on 2026-01-28 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("transcript", models.TextField()),
                ("blog_post", models.TextField()),
                ("seo_title", models.CharField(max_length=140)),
                ("meta_description", models.CharField(max_length=170)),
                ("tldr", models.TextField()),
                ("tweets", models.JSONField(default=list)),
                ("linkedin_post", models.TextField()),
                ("outline", models.JSONField(default=list)),
                ("key_takeaways", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
